#!/usr/bin/env php
<?php

define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);

chdir(__DIR__);

require FCPATH . 'app/Config/Paths.php';

$paths = new Config\Paths();

require rtrim($paths->systemDirectory, '\\/ ') . DIRECTORY_SEPARATOR . 'Boot.php';

define('ENVIRONMENT', $_SERVER['CI_ENVIRONMENT'] ?? 'development');

exit(CodeIgniter\Boot::bootSpark($paths));
